services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - DB_CONN_STR=postgres://postgres:unsafe@postgres:5432/postgres
      - DISCORD_TOKEN=SECRET
  postgres:
    image: "postgres:13.4-alpine"
    environment:
      - POSTGRES_PASSWORD=unsafe
  nginx:
    image: "nginx:1.21.3-alpine"
    ports:
      - "80:80"
      - "443:443"
